# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toxiccomments',
            old_name='comment_id',
            new_name='comment_user_id',
        ),
        migrations.AddField(
            model_name='toxiccomments',
            name='comment_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
